version: "2"
services:
    redis:
        image: redis
    # selenium:
    #     image: selenium/standalone-chrome:3.141.59-20200326
    #     volumes:
    #         - /dev/shm:/dev/shm
    #     ports:
    #         - 4444:4444
    webapp:
        build: .
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            # - CELERY_RESULT_BACKEND=redis://redis:6379
            - FLASK_APP=webapp 
            - FLASK_ENV=development
            - FLASK_APP_PORT=5000
        ports:
            - 5000:5000
        links:
            - redis
            # - selenium
        depends_on:
            - redis
            # - selenium